name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: todo
          MYSQL_ROOT_PASSWORD: root
        ports:
          - "3306:3306"
        options: --health-cmd="mysqladmin ping -h 127.0.0.1" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install coverage

      - name: Run Migrations
        run: |
          cd todoapp
          python manage.py migrate --settings=todoapp.settings_ci

      - name: Run Tests with Coverage
        run: |
          cd todoapp
          coverage run manage.py test --settings=todoapp.settings_ci
          coverage report

      - name: Lint Code
        run: |
          pip install flake8
          flake8 todoapp --count --select=E9,F63,F7,F82 --show-source --statistics
