name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint mysqlclient

    - name: Wait for MySQL
      run: |
        until mysqladmin ping -h127.0.0.1 -uroot -proot --silent; do
          echo "Waiting for database connection..."
          sleep 5
        done

    - name: Run Pylint
      run: pylint **/*.py

    - name: Run Django Tests
      working-directory: ./todoapp
      env:
        DB_NAME: test_db
        DB_USER: root
        DB_PASSWORD: root
        DB_HOST: 127.0.0.1
        GITHUB_ACTIONS: "true"
      run: |
        python manage.py migrate --noinput
        python manage.py test
