name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_pass
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --character-set-server=utf8mb4
          --collation-server=utf8mb4_unicode_ci
          --default-authentication-plugin=mysql_native_password
          --default-storage-engine=INNODB

    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pylint   # ✅ install pylint

    - name: Run Pylint
      run: |
        pylint **/*.py  # ✅ runs linting on all Python files

    - name: Wait for MySQL
      run: |
        until mysql -h 127.0.0.1 -utest_user -ptest_pass -e "SELECT 1;" test_db; do
          echo "⏳ Waiting for MySQL..."
          sleep 5
        done

    - name: Run Migrations
      working-directory: ./todoapp
      env:
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_pass
        DB_HOST: 127.0.0.1
      run: |
        python manage.py migrate --noinput

    - name: Run Tests
      working-directory: ./todoapp
      env:
        DB_NAME: test_db
        DB_USER: test_user
        DB_PASSWORD: test_pass
        DB_HOST: 127.0.0.1
      run: |
        python manage.py test
